name: Desktop Releases

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Targeting two versions of macOS in order to build binaries for both ARM (M1 etc.) and Intel processors.
        os: [ ubuntu-latest, macOS-latest, macos-13, windows-latest ]
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build Binary
        id: buildBinary
        env:
          TARGET_OS: ${{ matrix.target }}
        run: ./gradlew packageDistributionForCurrentOS
        shell: bash

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/main/dmg/*
            composeApp/build/compose/binaries/main/deb/*
            composeApp/build/compose/binaries/main/msi/*
