name: Renovate PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, android ]
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Check if actor is Renovate bot
        run: |
          if [ "${{ github.actor }}" = "renovate[bot]" ]; then
            echo "Renovate bot triggered this action"
          else
            echo "This action was not triggered by Renovate bot"
          fi

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run Tests with Gradle
        run: ./gradlew test
